# Generated by Django 5.2.5 on 2025-09-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Client', 'Client'), ('Admin', 'Admin')], default='Client', max_length=20),
        ),
    ]
