# Generated by Django 5.2.5 on 2025-10-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Pending', 'Pending'), ('Complete', 'Complete'), ('Canceled', 'Canceled')], default='Unpaid', max_length=20),
        ),
    ]
